apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-cms-ms-v1-deployment
  labels:
    app: alpha-backend-cms-ms-v1-deployment
spec:
  selector:
    matchLabels:
      app: alpha-backend-cms-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-cms-ms-v1-deployment
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ; sleep 2; done;']
      containers:
        - name: alpha-backend-cms-ms-v1-container
          image: alphadevprojet.azurecr.io/alpha-backend-cms-ms-v1@sha256:592bd84e559ffdcc684d3ea0352ae2aba91f130df0ee54b5ce475dd31320463d
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-cms-ms-v1-service
spec:
  selector:
    app: alpha-backend-cms-ms-v1-deployment
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
