version: '3.8'

services:
  app:
    container_name: alpha-backend-api-gateway-v1
    build:
      context: .
      dockerfile: Dockerfile
      # pass build args from .env file
      args:
        NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./.env:/.env
    # command: "npm start" # Uncomment if you need to override CMD defined in Dockerfile
