apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-api-gateway-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: alpha-backend-api-gateway-v1-deployment
  type: ClusterIP