apiVersion: v1
kind: Service
metadata:
  name: alpha-admin-service
  namespace: alpha
spec:
  ports:
  - port: 4137
    protocol: TCP
    targetPort: 4137
  selector:
    app: alpha-admin-deployment
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-api-gateway-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: alpha-backend-api-gateway-v1-deployment
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-cms-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: alpha-backend-cms-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-health-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: alpha-backend-health-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-notification-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: alpha-backend-notification-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-user-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: alpha-backend-user-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-rabbitmq-service
  namespace: alpha
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: alpha-rabbitmq
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-admin-deployment
  name: alpha-admin-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-admin-deployment
  template:
    metadata:
      labels:
        app: alpha-admin-deployment
    spec:
      containers:
      - image: alphadev.azurecr.io/alpha-admin@sha256:be9e15fe2a448183f20b5d86034e2de387e139d8368f8686663c1fdf664fcf18
        imagePullPolicy: IfNotPresent
        name: alpha-admin-container
        ports:
        - containerPort: 4137
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-backend-api-gateway-v1-service 3000; do echo waiting for
          backend ; sleep 2; done;
        image: busybox:1.28
        name: wait-for-api-gateway
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-api-gateway-v1-deployment
  name: alpha-backend-api-gateway-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-api-gateway-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-api-gateway-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3000"
        - name: APP_NAME
          value: alpha-api-gateway
        - name: APP_API_PREFIX
          value: /api/gateway/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-health-ms-v1-service:3004
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/health-ms/v1
        - name: USER_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: USER_SERVICE_API_PREFIX
          value: /api/user-ms/v1
        - name: CMS_SERVICE_BASE_URL
          value: http://alpha-backend-cms-ms-v1-service:3003
        - name: CMS_SERVICE_API_PREFIX
          value: /api/content-ms/v1
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: apigateway_queue
        - name: SUPER_ADMIN_TOKEN
          value: '@su93r@dm1n'
        - name: NOTFICATION_SERVICE_BASE_URL
          value: http://alpha-backend-notification-ms-v1-service:3002
        - name: NOTFICATION_SERVICE_API_PREFIX
          value: /api/notification-ms/v1
        image: alphadev.azurecr.io/alpha-backend-api-gateway-v1@sha256:f9cab60703fe640bd6ed1ee6645216c60d31196b623d2b38d1c700017c39640d
        imagePullPolicy: IfNotPresent
        name: alpha-backend-api-gateway-v1-container
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-cms-ms-v1-deployment
  name: alpha-backend-cms-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-cms-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-cms-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3003"
        - name: APP_NAME
          value: alpha-content-ms-v1
        - name: APP_API_PREFIX
          value: /api/content-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: cms_queue
        image: alphadev.azurecr.io/alpha-backend-cms-ms-v1@sha256:b9aac5884b4f73e851691d8c3518092479b5090f78c44125106882dc8b1e543d
        name: alpha-backend-cms-ms-v1-container
        ports:
        - containerPort: 3003
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-health-ms-v1-deployment
  name: alpha-backend-health-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-health-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-health-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3004"
        - name: APP_NAME
          value: alpha-health-ms-v1
        - name: APP_API_PREFIX
          value: /api/health-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: health_queue
        image: alphadev.azurecr.io/alpha-backend-health-ms-v1@sha256:97ab7baf47be5f6376f8915c8e7046113ef1102507a7b53cf3dbdaf7664fc3f6
        imagePullPolicy: IfNotPresent
        name: alpha-backend-health-ms-v1-container
        ports:
        - containerPort: 3004
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 150m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-notification-ms-v1-deployment
  name: alpha-backend-notification-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-notification-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-notification-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3002"
        - name: APP_NAME
          value: alpha-notification-ms-v1
        - name: APP_API_PREFIX
          value: /api/notification-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: notification_queue
        - name: SENDGRID_API_KEY
          value: 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
        - name: SENDGRID_FROM_NAME
          value: Aster Admin
        - name: SENDGRID_FROM_EMAIL
          value: admin@astercircular.co
        image: alphadev.azurecr.io/alpha-backend-notification-ms-v1@sha256:f88ac1987481fa0369f355b2d997574fdbaccdfe297a7cf1be328df84df913da
        imagePullPolicy: IfNotPresent
        name: alpha-backend-notification-ms-v1-container
        ports:
        - containerPort: 3002
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-user-ms-v1-deployment
  name: alpha-backend-user-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-user-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-user-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3001"
        - name: APP_NAME
          value: alpha-user-ms-v1
        - name: APP_API_PREFIX
          value: /api/user-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: user_queue
        image: alphadev.azurecr.io/alpha-backend-user-ms-v1@sha256:8a1969d86788e14b11af1c44bae0d13fb452441fb2cccd69b51d06d8c039a8fe
        imagePullPolicy: IfNotPresent
        name: alpha-backend-user-ms-v1-conatiner
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-rabbitmq
  name: alpha-rabbitmq
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-rabbitmq
  template:
    metadata:
      labels:
        app: alpha-rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        image: rabbitmq:3
        name: alpha-rabbitmq-container
        ports:
        - containerPort: 5672
      hostname: alpha-rabbitmq
