apiVersion: v1
kind: Service
metadata:
  name: alpha-admin-service
  namespace: alpha
spec:
  ports:
  - port: 4173
    protocol: TCP
    targetPort: 4173
  selector:
    app: alpha-admin-deployment
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-api-gateway-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: alpha-backend-api-gateway-v1-deployment
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-cms-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: alpha-backend-cms-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-health-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: alpha-backend-health-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-notification-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: alpha-backend-notification-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-user-ms-v1-service
  namespace: alpha
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: alpha-backend-user-ms-v1-deployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-rabbitmq-service
  namespace: alpha
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: alpha-rabbitmq
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-admin-deployment
  name: alpha-admin-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-admin-deployment
  template:
    metadata:
      labels:
        app: alpha-admin-deployment
    spec:
      containers:
      - image: alphadev.azurecr.io/alpha-admin@sha256:cdd0142a0b4bb31b08d6b5c2d7c166ebb1119df2999f0e8f225bc8775d677567
        imagePullPolicy: IfNotPresent
        name: alpha-admin-container
        ports:
        - containerPort: 4137
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.2Gi
            memory: 0.2Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-backend-api-gateway-v1-service 3000; do echo waiting for
          backend ; sleep 2; done;
        image: busybox:1.28
        name: wait-for-api-gateway
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-api-gateway-v1-deployment
  name: alpha-backend-api-gateway-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-api-gateway-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-api-gateway-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3000"
        - name: APP_NAME
          value: alpha-api-gateway
        - name: APP_API_PREFIX
          value: /api/gateway/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-health-ms-v1-service:3004
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/health-ms/v1
        - name: USER_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: USER_SERVICE_API_PREFIX
          value: /api/user-ms/v1
        - name: CMS_SERVICE_BASE_URL
          value: http://alpha-backend-cms-ms-v1-service:3003
        - name: CMS_SERVICE_API_PREFIX
          value: /api/content-ms/v1
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: apigateway_queue
        - name: SUPER_ADMIN_TOKEN
          value: '@su93r@dm1n'
        - name: NOTIFICATION_SERVICE_BASE_URL
          value: http://alpha-backend-notification-ms-v1-service:3002
        - name: NOTIFICATION_SERVICE_API_PREFIX
          value: /api/notification-ms/v1
        image: alphadev.azurecr.io/alpha-backend-api-gateway-v1@sha256:b4bd49bd2f47b4c72818f47543e0ce6491e84e202d881de636d01a436f301409
        imagePullPolicy: IfNotPresent
        name: alpha-backend-api-gateway-v1-container
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.2Gi
            memory: 0.2Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-cms-ms-v1-deployment
  name: alpha-backend-cms-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-cms-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-cms-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3003"
        - name: APP_NAME
          value: alpha-content-ms-v1
        - name: APP_API_PREFIX
          value: /api/content-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: cms_queue
        image: alphadev.azurecr.io/alpha-backend-cms-ms-v1@sha256:c76a435f7091c79e97217a1c2f46e91d7b776af9d3f9f6bef727899f610ea402
        name: alpha-backend-cms-ms-v1-container
        ports:
        - containerPort: 3003
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.2Gi
            memory: 0.2Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-health-ms-v1-deployment
  name: alpha-backend-health-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-health-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-health-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3004"
        - name: APP_NAME
          value: alpha-health-ms-v1
        - name: APP_API_PREFIX
          value: /api/health-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: health_queue
        image: alphadev.azurecr.io/alpha-backend-health-ms-v1@sha256:dfeac50e5837a5eb7c88b7832c59dc6bc81885b9db6f1c7ffe3a21d8199f2b6b
        imagePullPolicy: IfNotPresent
        name: alpha-backend-health-ms-v1-container
        ports:
        - containerPort: 3004
        resources:
          limits:
            cpu: 150m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 150m
            ephemeral-storage: .2Gi
            memory: 0.2Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-notification-ms-v1-deployment
  name: alpha-backend-notification-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-notification-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-notification-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3002"
        - name: APP_NAME
          value: alpha-notification-ms-v1
        - name: APP_API_PREFIX
          value: /api/notification-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: notification_queue
        - name: SENDGRID_API_KEY
          value: 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
        - name: SENDGRID_FROM_NAME
          value: Aster Admin
        - name: SENDGRID_FROM_EMAIL
          value: admin@astercircular.co
        image: alphadev.azurecr.io/alpha-backend-notification-ms-v1@sha256:a2dba940268f941ed2f448b38ccc51fbf38c47751bdb81d694723dda71b6e1e1
        imagePullPolicy: IfNotPresent
        name: alpha-backend-notification-ms-v1-container
        ports:
        - containerPort: 3002
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.2Gi
            memory: 0.2Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-backend-user-ms-v1-deployment
  name: alpha-backend-user-ms-v1-deployment
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-backend-user-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-user-ms-v1-deployment
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: local
        - name: PORT
          value: "3001"
        - name: APP_NAME
          value: alpha-user-ms-v1
        - name: APP_API_PREFIX
          value: /api/user-ms/v1
        - name: APP_DEBUG
          value: "true"
        - name: JWT_SECRET
          value: secret
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: HEALTH_SERVICE_BASE_URL
          value: http://alpha-backend-user-ms-v1-service:3001
        - name: HEALTH_SERVICE_API_PREFIX
          value: /api/v1/health
        - name: DB_HOST
          value: alpha-postgressql.postgres.database.azure.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: alphaadmin
        - name: DB_PASSWORD
          value: alphaadminpasswd543
        - name: DB_NAME
          value: alpha_database
        - name: RABBITMQ_HOST
          value: alpha-rabbitmq-service
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_QUEUE
          value: user_queue
        image: alphadev.azurecr.io/alpha-backend-user-ms-v1@sha256:58f3c006ec8696ce8699baa8f54561cc47da2cc459aafedc676d1c65edc33a4c
        imagePullPolicy: IfNotPresent
        name: alpha-backend-user-ms-v1-conatiner
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 0.5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: 0.2Gi
            memory: 0.2Gi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ;
          sleep 2; done;
        image: busybox:1.28
        name: wait-for-rabbitmq
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
          requests:
            cpu: 250m
            ephemeral-storage: .5Gi
            memory: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-rabbitmq
  name: alpha-rabbitmq
  namespace: alpha
spec:
  selector:
    matchLabels:
      app: alpha-rabbitmq
  template:
    metadata:
      labels:
        app: alpha-rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        image: rabbitmq:3
        name: alpha-rabbitmq-container
        ports:
        - containerPort: 5672
      hostname: alpha-rabbitmq
