apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-rabbitmq
  labels:
    app: alpha-rabbitmq
spec:
  selector:
    matchLabels:
      app: alpha-rabbitmq
  template:
    metadata:
      labels:
        app: alpha-rabbitmq
    spec:
      hostname: alpha-rabbitmq
      containers:
      - name: alpha-rabbitmq-container
        image: rabbitmq:3
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-rabbitmq-service
spec:
  selector:
    app: alpha-rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  type: ClusterIP
