apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-user-ms-v1-deployment
  labels:
    app: alpha-backend-user-ms-v1-deployment
spec:
  selector:
    matchLabels:
      app: alpha-backend-user-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-user-ms-v1-deployment
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ; sleep 2; done;']
      containers:
        - name: alpha-backend-user-ms-v1-conatiner
          image: alphadev.azurecr.io/alpha-backend-user-ms-v1@sha256:7055e140a068e8a724c82960c671190d6b56d8e2c4e6149c8326b05e5ebbe87e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: 0.2Gi
              memory: 0.2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-user-ms-v1-service
spec:
  selector:
    app: alpha-backend-user-ms-v1-deployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
