apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-health-ms-v1-deployment
  labels:
    app: alpha-backend-health-ms-v1-deployment
spec:
  selector:
    matchLabels:
      app: alpha-backend-health-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-health-ms-v1-deployment
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ; sleep 2; done;']
      containers:
        - name: alpha-backend-health-ms-v1-container
          image: alphadev.azurecr.io/alpha-backend-health-ms-v1@sha256:7395cc0556e1837d17e703b965541d2487c9c9e353bb85efcf0332aa5df12f4f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 150m
              ephemeral-storage: .2Gi
              memory: 0.2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-health-ms-v1-service
spec:
  selector:
    app: alpha-backend-health-ms-v1-deployment
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
