apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-admin-deployment
  labels:
    app: alpha-admin-deployment
spec:
  selector:
    matchLabels:
      app: alpha-admin-deployment
  template:
    metadata:
      labels:
        app: alpha-admin-deployment
    spec:
      initContainers:
        - name: wait-for-api-gateway
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z alpha-backend-api-gateway-v1-service 3000; do echo waiting for backend ; sleep 2; done;']
      containers:
        - name: alpha-admin-container
          image: alphadev.azurecr.io/alpha-admin@sha256:763573470a1b40e2f523eea06c80c29aa42940091365baead694bd834f665134
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4137
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: 0.2Gi
              memory: 0.2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-admin-service
spec:
  selector:
    app: alpha-admin-deployment
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 4173
  type: LoadBalancer
