apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-api-gateway-v1-deployment
  labels:
    app: alpha-backend-api-gateway-v1-deployment
spec:
  selector:
    matchLabels:
      app: alpha-backend-api-gateway-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-api-gateway-v1-deployment
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ; sleep 2; done;']
      containers:
        - name: alpha-backend-api-gateway-v1-container
          image: alphadev.azurecr.io/alpha-backend-api-gateway-v1@sha256:1431ce2c817c882e5813a2c0b0bb88a4c8e69b3753ee2e4fb56d80af08b80391
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-api-gateway-v1-service
spec:
  selector:
    app: alpha-backend-api-gateway-v1-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
