apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-user-ms-v1-deployment
  labels:
    app: alpha-backend-user-ms-v1-deployment
spec:
  selector:
    matchLabels:
      app: alpha-backend-user-ms-v1-deployment
  template:
    metadata:
      labels:
        app: alpha-backend-user-ms-v1-deployment
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: .5Gi
              memory: 0.5Gi
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z alpha-rabbitmq-service 5672; do echo waiting for rabbitmq ; sleep 2; done;']
      containers:
        - name: alpha-backend-user-ms-v1-conatiner
          image: alphadev.azurecr.io/alpha-backend-user-ms-v1@sha256:af20c8f2841dac57ef6686bcb1228e97674ebd91e80d3a0d642d30e84859a4be
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
            requests:
              cpu: 250m
              ephemeral-storage: 0.5Gi
              memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-user-ms-v1-service
spec:
  selector:
    app: alpha-backend-user-ms-v1-deployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
