apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-notification-ms-v1-deployment
spec:
  template:
    spec:
      containers:
      - name: alpha-backend-notification-ms-v1-container
        env:
          - name: NODE_ENV
            value: "local"
          - name: PORT
            value: "3002"
          - name: APP_NAME
            value: "alpha-notification-ms-v1"
          - name: APP_API_PREFIX
            value: "/api/notification-ms/v1"
          - name: APP_DEBUG
            value: "true"
          - name: JWT_SECRET
            value: "secret"
          - name: JWT_EXPIRES_IN
            value: "1d"
          - name: HEALTH_SERVICE_BASE_URL
            value: "http://alpha-backend-user-ms-v1-service:3001"
          - name: HEALTH_SERVICE_API_PREFIX
            value: "/api/v1/health"
          - name: DB_HOST
            value: "alpha-postgressql.postgres.database.azure.com"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "alphaadmin"
          - name: DB_PASSWORD
            value: "alphaadminpasswd543"
          - name: DB_NAME
            value: "alpha_database"
          - name: RABBITMQ_HOST
            value: alpha-rabbitmq-service
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USERNAME
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
          - name: RABBITMQ_QUEUE
            value: "notification_queue"
          - name: SENDGRID_API_KEY
            value: "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"
          - name: SENDGRID_FROM_NAME
            value: "Aster Admin"
          - name: SENDGRID_FROM_EMAIL
            value: "admin@astercircular.co"
