apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-rabbitmq
spec:
  template:
    spec:
      containers:
      - name: alpha-rabbitmq-container
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
